-- Migration 005: AI conversation persistence tables
-- Stores multi-turn AI chat conversations and their messages
-- Uses CREATE TABLE IF NOT EXISTS for idempotency (safe to re-run)

-- Conversations table (DB-01)
CREATE TABLE IF NOT EXISTS ai_conversations (
    id          TEXT PRIMARY KEY,              -- UUID generated by Rust
    title       TEXT NOT NULL DEFAULT '',      -- Auto-titled from first user message (max 50 chars)
    created_at  INTEGER NOT NULL               -- Unix timestamp in seconds
);

-- Messages table (DB-02)
CREATE TABLE IF NOT EXISTS ai_messages (
    id                TEXT PRIMARY KEY,        -- UUID generated by Rust
    conversation_id   TEXT NOT NULL,           -- FK to ai_conversations.id
    role              TEXT NOT NULL,            -- 'user' or 'assistant'
    content           TEXT NOT NULL,
    metadata_json     TEXT,                    -- Nullable JSON blob for future extensibility
    created_at        INTEGER NOT NULL,        -- Unix timestamp in seconds
    FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE
);

-- Index for fast message lookups by conversation
CREATE INDEX IF NOT EXISTS idx_ai_messages_conversation_id ON ai_messages(conversation_id);

-- Index for listing conversations ordered by most recent
CREATE INDEX IF NOT EXISTS idx_ai_conversations_created_at ON ai_conversations(created_at);
